// ============================================================
// web/ <-> android assets drift checker (CI)
// web/ is the single source of truth (capacitor.config.js webDir).
// The committed copy under android/app/src/main/assets/public/ must match,
// otherwise a build done without `cap sync` would silently ship stale code.
// Exits 1 with a report when drift is found.
// ============================================================
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const WEB = path.join(__dirname, '..', 'web');
const DEST = path.join(__dirname, '..', 'android', 'app', 'src', 'main', 'assets', 'public');

// Files generated by `cap sync` into assets/public that have no web/ source.
const SYNC_GENERATED = new Set(['cordova.js', 'cordova_plugins.js']);

function walk(dir, base = '') {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...walk(path.join(dir, entry.name), rel));
    else out.push(rel);
  }
  return out.sort();
}

function sha256(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

const webFiles = walk(WEB);
const destFiles = walk(DEST);

let failed = 0;

// 1) every web/ file must exist in assets with identical content
for (const rel of webFiles) {
  const destPath = path.join(DEST, rel);
  if (!fs.existsSync(destPath)) {
    failed++;
    console.error(`MISSING in assets: ${rel}`);
    continue;
  }
  if (sha256(path.join(WEB, rel)) !== sha256(destPath)) {
    failed++;
    console.error(`DRIFT: ${rel}`);
  }
}

// 2) assets files with no web/ source (stale leftovers) — sync-generated ones are fine
for (const rel of destFiles) {
  if (SYNC_GENERATED.has(rel)) continue;
  if (!webFiles.includes(rel)) {
    failed++;
    console.error(`STALE in assets (no web/ source): ${rel}`);
  }
}

if (failed > 0) {
  console.error(`\n${failed}건의 drift 감지 — web/ 기준으로 동기화하세요: (예) (cd android && npx cap sync) 또는 수동 복사`);
  process.exit(1);
}
console.log(`${webFiles.length}개 파일 — web/ ↔ android assets 동기화 상태 일치`);
